#!/usr/bin/env bash

set -euo pipefail

HOST_OS_RAW="$(uname -s)"
HOST_ARCH_RAW="$(uname -m)"

HOST_OS="${HOST_OS_RAW,,}"
HOST_ARCH="${HOST_ARCH_RAW,,}"

case "${HOST_ARCH}" in
    x86_64 | amd64)
        ARTIFACT_ARCH="amd64"
        ;;
    aarch64 | arm64)
        ARTIFACT_ARCH="arm64"
        ;;
    *)
        echo "unsupported host architecture: ${HOST_ARCH_RAW}" >&2
        exit 1
        ;;
esac

ARTIFACT_NAME="qemu"
# nearest qemu tagged version
ARTIFACT_BASE_VERSION="11.0.0"
# when not blank, append another element to version, begin count from 1
ARTIFACT_SERIAL=

ARTIFACT_VERSION="${ARTIFACT_BASE_VERSION}${ARTIFACT_SERIAL:+.${ARTIFACT_SERIAL}}"
ARTIFACT_BASENAME="${ARTIFACT_NAME}-${HOST_OS}-${ARTIFACT_ARCH}-${ARTIFACT_VERSION}"

QEMU_REPO="https://codeberg.org/ziglang/qemu.git"
QEMU_REV=51688f91f6a3ce7b69df1c7b601fcb22fae3a275
QEMU_BASENAME="${ARTIFACT_NAME}-${ARTIFACT_VERSION}"

WORKDIR() {
    echo "workdir: $(pwd)"
    mkdir -p "$1"
    cd "$1"
}

RUN() {
    echo "run: $*"
    "$@"
}

WORKDIR /work/src
RUN git init "${QEMU_BASENAME}"
WORKDIR "/work/src/${QEMU_BASENAME}"
RUN git remote add origin "${QEMU_REPO}"
RUN git fetch --depth=1 origin "${QEMU_REV}"
RUN git checkout --detach FETCH_HEAD

WORKDIR "/work/out/${QEMU_BASENAME}"
RUN "/work/src/${QEMU_BASENAME}/configure" \
    --prefix="/work/dst/${ARTIFACT_BASENAME}" \
    --disable-debug-info \
    --disable-system \
    --disable-werror \
    --enable-linux-user \
    --static

RUN make "-j$(nproc)"
RUN make "-j$(nproc)" install

WORKDIR /work/artifact
RUN tar --zstd -cf "${ARTIFACT_BASENAME}.tar.zst" -C /work/dst "${ARTIFACT_BASENAME}"
